<div class="conteudo2">
	<div class="topo">
		<img src="/idealize/public/img/topo.png" alt="Topo">
	</div>
	<div class="usuarios">		
		<h1>Alteração de categoria</h1>
		<?php			
			$form = $this->form;
			$form->setAttribute('action',$this->url('idealize-admin-interna',array('controller'=>'categoria','action'=>'edit')));
			$form->prepare();
			echo $this->form()->openTag($form);
		?>
		<table class="tabela-pessoa">
			<tr>
				<td colspan="2"><?php echo $this->formHidden($form->get('id')); ?></td>
			</tr>
			<tr>
				<td class="lbl">Categoria:</td>
				<td><?php echo $this->formRow($form->get('categoria')); ?></td>
			</tr>
			<tr>
				<td class="lbl">Imagem:</td>
				<td style="padding:10px 0;"><?php echo $this->formRow($form->get('imagem')); ?></td>
			</tr>
			<?php 
				$image = $this->form->getElements()['imagem']->getValue();
				if(!empty($image)){					
			?>
					<tr>
						<td class="lbl">Imagem Atual:</td>
						<td style="padding:10px 0;"><img src="/idealize/public/img/categoria/<?php echo $this->form->getElements()['imagem']->getValue(); ?>" alt="" style="width:200px; float:left;"></td>				
					</tr>			
			<?php
				}
			?>
			<tr>
				<td colspan="2">
					<a href="/idealize/public/admin/categoria" class="btnVoltar">Voltar</a>
					<?php echo $this->formSubmit($form->get('submit'));?>
				</td>				
			</tr>
		</table>
		<?php			
			echo $this->form()->closeTag();
		?>
	</div>
</div>