<div class="conteudo2">
	<div class="topo">
		<img src="img/topo.png" alt="Topo">
	</div>
	<div class="menu">
		<h1>Selecione uma opção:</h1>
		<a href="/idealize/public/admin/usuarios">Cadastrar Usuários</a>
		<a href="/idealize/public/admin/pontos">Cadastrar Pontos</a>
		<a href="/idealize/public/admin/categoria">Cadastrar Categoria</a>
		<a href="/idealize/public/admin/regulamento">Cadastrar Regulamento</a>
		<a href="/idealize/public/admin/premiacao">Cadastrar Premiação</a>
		<a href="<?php echo $this->url('idealize-admin-logout')?>">Sair</a>
	</div>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>	
	<br>
	<br>
</div>