<section class="login">
	<img src="/img/logo.png" alt="Villagres" />
	<h1><?php echo utf8_encode('Área Restrita')?></h1>	
		
	<?php 
		$form = $this->form;
		$form->prepare();
		$form->setAttribute('action',$this->url(NULL,array('controller' => 'Index','action' => 'process')));
		$form->setAttribute('method','post');
		echo $this->form()->openTag($form);
	?>
	<dl class="zend_form">
		<dt><?php echo $this->formLabel($form->get('txtUsuario'));?></dt>
		<dd>
			<?php 
				echo $this->formElement($form->get('txtUsuario'));				
			?>
		</dd>	
		<dt><?php echo $this->formLabel($form->get('txtSenha'));?></dt>
		<dd>
			<?php 
				echo $this->formElement($form->get('txtSenha'));				
			?>
		</dd>
		<dd>
			<?php 
				echo $this->formElement($form->get('btnLogar'));
			?>
		</dd>
	</dl>
	<?php echo $this->form()->closeTag();?>
</section>