<?php

namespace DoctrineORMModule\Proxy\__CG__\Idealize\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ponto extends \Idealize\Entity\Ponto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'pontos', 'formato', 'dtPontos', 'metragem', 'lojaParceira', 'idPessoa');
        }

        return array('__isInitialized__', 'id', 'pontos', 'formato', 'dtPontos', 'metragem', 'lojaParceira', 'idPessoa');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ponto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPontos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPontos', array());

        return parent::getPontos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPontos($pontos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPontos', array($pontos));

        return parent::setPontos($pontos);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormato', array());

        return parent::getFormato();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormato($formato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormato', array($formato));

        return parent::setFormato($formato);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtPontos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtPontos', array());

        return parent::getDtPontos();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtPontos($dtPontos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtPontos', array($dtPontos));

        return parent::setDtPontos($dtPontos);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetragem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetragem', array());

        return parent::getMetragem();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetragem($metragem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetragem', array($metragem));

        return parent::setMetragem($metragem);
    }

    /**
     * {@inheritDoc}
     */
    public function getLojaParceira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLojaParceira', array());

        return parent::getLojaParceira();
    }

    /**
     * {@inheritDoc}
     */
    public function setLojaParceira($lojaParceira)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLojaParceira', array($lojaParceira));

        return parent::setLojaParceira($lojaParceira);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPessoa', array());

        return parent::getIdPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPessoa($idPessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPessoa', array($idPessoa));

        return parent::setIdPessoa($idPessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
