<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(utf8_encode('Cerâmica Villagrês'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/estilo.css'))
                        ->prependStylesheet($this->basePath('css/diapo.css')) 
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))      
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))            
        ; ?>		        	
			<!--[if !IE]><!--><script type='text/javascript' src='js/jquery.mobile-1.0rc2.customized.min.js'></script><!--<![endif]-->
			<script type='text/javascript' src='js/jquery.easing.1.3.js'></script> 
			<script type='text/javascript' src='js/jquery.hoverIntent.minified.js'></script> 
			<script type='text/javascript' src='js/diapo.js'></script> 		
		 	<script type="text/javascript">
				$(function(){
					$('.pix_diapo').diapo();
				});		
			</script> 
    </head>
    <body>       	  	    	 	                                
        <div class="container">
            <?php echo $this->content; ?>            
        </div> <!-- /container -->                      
        <?php echo $this->inlineScript() ?>
    </body>
</html>
